services:
  user_service:
    build:
      context: src/services/user_service
      dockerfile: dockerfile
    environment:                                                                                                                                                                                             
        DB_HOST: host.docker.internal                                                                                                                                                                          
        DB_PORT: 5432                                                                                                                                                                                          
        DB_NAME: meu_banco                                                                                                                                                                                     
        DB_USER: admin                                                                                                                                                                                         
        DB_PASSWORD: senha123                                                                                                                                                                                  
    ports:                                                                                                                                                                                                   
        - "8000:8000"

  api_gateway:
    build:
      context: src/services/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user_service